# .github/workflows/terraform-destroy.yml
name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      plan:
        description: 'Path to the plan file'
        required: true
        default: 'plan.tfplan'

permissions:
  id-token: write
  contents: read

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    environment: production # This environment should be configured with required reviewers
    env:
      TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
      TF_VAR_region: ${{ secrets.REGION }}
      TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          project_id: '${{ secrets.PROJECT_ID }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_POOL }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
